// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Context;

namespace WebApi.Migrations
{
    [DbContext(typeof(KitapContext))]
    [Migration("20200108135915_DbInit")]
    partial class DbInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebApi.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dtCreate");

                    b.Property<DateTime>("dtLastUpdate");

                    b.Property<bool>("isDelet");

                    b.Property<string>("sAdi")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("sKodu")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.ToTable("kategori");
                });

            modelBuilder.Entity("WebApi.Models.Kitap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("KategoriId");

                    b.Property<int?>("YazarId");

                    b.Property<DateTime>("dtCreate");

                    b.Property<DateTime>("dtLastUpdate");

                    b.Property<DateTime>("dtYayinTarihi");

                    b.Property<bool>("isDelet");

                    b.Property<decimal>("ldKitapFiyat");

                    b.Property<string>("sAciklama")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("sISBN")
                        .IsRequired()
                        .HasMaxLength(13);

                    b.Property<string>("sKitapAdi")
                        .IsRequired()
                        .HasMaxLength(120);

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.HasIndex("YazarId");

                    b.ToTable("kitap");
                });

            modelBuilder.Entity("WebApi.Models.Yazar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dtCreate");

                    b.Property<DateTime>("dtDogumTarih");

                    b.Property<DateTime>("dtLastUpdate");

                    b.Property<bool>("isDelet");

                    b.Property<string>("sAdi")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("sSoyadi")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("sTckn")
                        .HasMaxLength(11);

                    b.Property<string>("sYazarHakkinda");

                    b.HasKey("Id");

                    b.ToTable("yazar");
                });

            modelBuilder.Entity("WebApi.Models.Kitap", b =>
                {
                    b.HasOne("WebApi.Models.Kategori", "Kategori")
                        .WithMany()
                        .HasForeignKey("KategoriId");

                    b.HasOne("WebApi.Models.Yazar", "Yazar")
                        .WithMany()
                        .HasForeignKey("YazarId");
                });
#pragma warning restore 612, 618
        }
    }
}
